defaults:
  env:
    name: "enduro"

  training:
    seed: 42
    n_epochs: 10000
    sampler: "ray"
    num_segs_per_batch: 50
    seg_length: 50
    num_training_steps: 800 
    # seed_episodes: 2
    grad_clip: 100
    max_episode_length: null 
    target_update_freq: 50
    buf_capacity: 2e6
    

  samplers:
    agent:
      n: 4
      eps: 1

    log:
      n: 1
      eps: 1

    init:
      n: 5
      eps: 1

  loss_scales:
    reward: 1
    discount: 5
    recon: 1
    kl: 0.1

  logging:
    log_freq: 5

  world:
    lr: 0.0002
    eps: 1e-5
    wd: 1e-6
    pretrain_steps: 1000

  rssm:
    stoch_state_classes: 32
    stoch_state_size: 32
    det_state_size: 600
    alpha: 0.8
    act: "nn.functional.elu"

  actor:
    grad: "reinforce"
    ent_scale: 1e-3
    units: [400, 400, 400, 400]
    lr: 4e-5
    eps: 1e-5
    wd: 1e-6

  critic:
    imag_horizon: 15
    lam: 0.95
    units: [400, 400, 400, 400]
    lr: 1e-4
    eps: 1e-5
    wd: 1e-6

  reward_head:
    units: [400, 400, 400, 400]
    Activation: "torch.nn.ELU"

  discount_head:
    units: [400, 400, 400, 400]
    Activation: "torch.nn.ELU"

  image:
    color_channels: 3
    height: 64
    width: 64

  image_encoder:
    Activation: "nn.ELU"
    N: 48

  image_decoder:
    Activation: "nn.ELU"
    N: 48

debug:
  env:
    name: "breakout"

  training:
    seed: 42
    lr: 0.0002
    n_epochs: 100
    sampler: "local"
    num_segs_per_batch: 5
    seg_length: 20 
    num_training_steps: 3 
    seed_episodes: 2
    max_episode_length: 150 
    target_update_freq: 2

  samplers:
    agent:
      n: 1
      eps: 1

    log:
      n: 1
      eps: 1

    init:
      n: 1
      eps: 1

  rssm:
    stoch_state_classes: 16
    stoch_state_size: 16
    det_state_size: 100
    alpha: 0.8
    beta: 0.1
    act: "nn.functional.elu"

  critic:
    imag_horizon: 5

  world:
    pretrain: 1
    pretrain_steps: 10

  logging:
    log_vid_freq: 2
    log_freq: 2

  reward_head:
    units: [100, 100]
    Activation: "torch.nn.ELU"

  discount_head:
    units: [100, 100]
    Activation: "torch.nn.ELU"

  image:
    color_channels: 3
    height: 64
    width: 64

  image_encoder:
    Activation: "nn.ELU"
    N: 32

  image_decoder:
    Activation: "nn.ELU"
    N: 32

